# Generated by Django 2.2.2 on 2019-06-24 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allocation',
            old_name='Project_name',
            new_name='project_name',
        ),
    ]
